// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eocymxqhhemgkpmbhvzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvY3lteHFoaGVtZ2twbWJodnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTQ0NTYsImV4cCI6MjA2NDk5MDQ1Nn0.NWPk1UkbJxxsPQ1yTILRAp9S8bxDQHdLe0TQFT6Hnvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);